name: Coveralls_Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.10"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"

      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m unittest
        continue-on-error: true

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: success() || failure()
        
      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@v2
        if: success() || failure()